import type { Inquiry, Listing } from "@/types";

const demoListingImages = {
  thar: "https://placehold.co/1200x800/png?text=Mahindra+Thar",
  creta: "https://placehold.co/1200x800/png?text=Hyundai+Creta",
  city: "https://placehold.co/1200x800/png?text=Honda+City",
};

export const demoListings: Listing[] = [
  {
    id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    createdAt: "2026-03-24T10:00:00.000Z",
    updatedAt: "2026-03-24T10:00:00.000Z",
    stockNumber: "SCB-101",
    numberPlate: "PB08-TH-2022",
    make: "Mahindra",
    model: "Thar",
    variant: "LX Hard Top Diesel MT",
    year: 2022,
    fuel: "Diesel",
    transmission: "Manual",
    kmDriven: 24000,
    color: "Black",
    ownerCount: 1,
    price: 1645000,
    location: "Jalandhar",
    description:
      "Well-maintained Mahindra Thar with clean ownership history, complete paperwork, and showroom-ready condition.",
    sellerType: "dealer",
    status: "available",
    featured: true,
    coverImageUrl: demoListingImages.thar,
    images: [
      {
        id: "img-1",
        listingId: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        imageUrl: demoListingImages.thar,
        sortOrder: 0,
      },
    ],
    seller: {
      id: "seller-1",
      listingId: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
      sellerType: "dealer",
      name: "Singh Car Bazar",
      phone: "+91 7277131313",
      address:
        "B.M.C. Chowk, Shop No. 3-4, Near Desh Bhagat Hall, 10 G.T. Road, Jalandhar",
      notes: "Demo showroom seller",
    },
    buyer: null,
    documents: [],
  },
  {
    id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    createdAt: "2026-03-23T10:00:00.000Z",
    updatedAt: "2026-03-23T10:00:00.000Z",
    stockNumber: "SCB-102",
    numberPlate: "PB08-CR-2021",
    make: "Hyundai",
    model: "Creta",
    variant: "SX IVT Petrol",
    year: 2021,
    fuel: "Petrol",
    transmission: "Automatic",
    kmDriven: 31500,
    color: "White",
    ownerCount: 1,
    price: 1490000,
    location: "Jalandhar",
    description:
      "Popular family SUV in strong condition with premium interior, automatic transmission, and complete service support.",
    sellerType: "dealer",
    status: "available",
    featured: true,
    coverImageUrl: demoListingImages.creta,
    images: [
      {
        id: "img-2",
        listingId: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        imageUrl: demoListingImages.creta,
        sortOrder: 0,
      },
    ],
    seller: {
      id: "seller-2",
      listingId: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
      sellerType: "dealer",
      name: "Singh Car Bazar",
      phone: "+91 7277131313",
      address:
        "B.M.C. Chowk, Shop No. 3-4, Near Desh Bhagat Hall, 10 G.T. Road, Jalandhar",
      notes: "Demo showroom seller",
    },
    buyer: null,
    documents: [],
  },
  {
    id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
    createdAt: "2026-03-22T10:00:00.000Z",
    updatedAt: "2026-03-22T10:00:00.000Z",
    stockNumber: "SCB-103",
    numberPlate: "PB08-CT-2020",
    make: "Honda",
    model: "City",
    variant: "VX CVT",
    year: 2020,
    fuel: "Petrol",
    transmission: "Automatic",
    kmDriven: 41000,
    color: "Silver",
    ownerCount: 2,
    price: 1145000,
    location: "Jalandhar",
    description:
      "Clean sedan with smooth automatic drive, tasteful cabin condition, and updated service records.",
    sellerType: "private",
    status: "booked",
    featured: false,
    coverImageUrl: demoListingImages.city,
    images: [
      {
        id: "img-3",
        listingId: "cccccccc-cccc-cccc-cccc-cccccccccccc",
        imageUrl: demoListingImages.city,
        sortOrder: 0,
      },
    ],
    seller: {
      id: "seller-3",
      listingId: "cccccccc-cccc-cccc-cccc-cccccccccccc",
      sellerType: "private",
      name: "Karan Singh",
      phone: "+91 9876543210",
      address: null,
      notes: "Demo private seller",
    },
    buyer: null,
    documents: [],
  },
];

export const demoInquiries: Inquiry[] = [
  {
    id: "inq-1",
    listingId: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    name: "Harsh Gupta",
    phone: "+91 9988776655",
    email: "harsh@example.com",
    message: "Need more photos and best price for the Thar.",
    createdAt: "2026-03-25T11:15:00.000Z",
  },
  {
    id: "inq-2",
    listingId: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    name: "Simran Arora",
    phone: "+91 8877665544",
    email: "simran@example.com",
    message: "Please share finance options for the Creta.",
    createdAt: "2026-03-24T14:45:00.000Z",
  },
];
