import { createSlug } from "@/lib/utils";
import type { Inquiry, Listing } from "@/types";

const demoSeller = {
  id: "seller-1",
  sellerType: "dealer" as const,
  name: "Singh Car Bazar",
  phone: "+91 7277131313",
  address:
    "B.M.C. Chowk, Shop No. 3-4, Near Desh Bhagat Hall, 10 G.T. Road, Jalandhar",
  notes: "Primary demo seller profile",
};

export const demoListings: Listing[] = [
  {
    id: "car-1",
    slug: createSlug("mahindra", "thar", "2022"),
    stockNumber: "SCB-101",
    numberPlate: "PB08-TH-2022",
    make: "Mahindra",
    model: "Thar",
    variant: "LX Hard Top Diesel MT",
    year: 2022,
    registrationYear: 2022,
    fuel: "Diesel",
    transmission: "Manual",
    kmDriven: 24000,
    color: "Black",
    ownerNumber: 1,
    price: 1645000,
    location: "Jalandhar",
    description:
      "Well-maintained Mahindra Thar with clean ownership history, complete paperwork, and showroom-ready condition.",
    featured: true,
    status: "available",
    isPublished: true,
    sellerType: "dealer",
    seller: demoSeller,
    buyer: null,
    images: [
      {
        id: "img-1",
        listingId: "car-1",
        imageUrl: "",
        isFeatured: true,
        sortOrder: 0,
      },
      {
        id: "img-2",
        listingId: "car-1",
        imageUrl: "",
        isFeatured: false,
        sortOrder: 1,
      },
    ],
    documents: [],
    createdAt: "2026-03-24T10:00:00.000Z",
  },
  {
    id: "car-2",
    slug: createSlug("hyundai", "creta", "2021"),
    stockNumber: "SCB-102",
    numberPlate: "PB08-CR-2021",
    make: "Hyundai",
    model: "Creta",
    variant: "SX IVT Petrol",
    year: 2021,
    registrationYear: 2021,
    fuel: "Petrol",
    transmission: "Automatic",
    kmDriven: 31500,
    color: "White",
    ownerNumber: 1,
    price: 1490000,
    location: "Jalandhar",
    description:
      "Popular family SUV in strong condition with premium interior, automatic transmission, and complete service support.",
    featured: true,
    status: "available",
    isPublished: true,
    sellerType: "dealer",
    seller: demoSeller,
    buyer: null,
    images: [
      {
        id: "img-3",
        listingId: "car-2",
        imageUrl: "",
        isFeatured: true,
        sortOrder: 0,
      },
    ],
    documents: [],
    createdAt: "2026-03-23T10:00:00.000Z",
  },
  {
    id: "car-3",
    slug: createSlug("honda", "city", "2020"),
    stockNumber: "SCB-103",
    numberPlate: "PB08-CT-2020",
    make: "Honda",
    model: "City",
    variant: "VX CVT",
    year: 2020,
    registrationYear: 2020,
    fuel: "Petrol",
    transmission: "Automatic",
    kmDriven: 41000,
    color: "Silver",
    ownerNumber: 2,
    price: 1145000,
    location: "Jalandhar",
    description:
      "Clean sedan with smooth automatic drive, tasteful cabin condition, and updated service records.",
    featured: false,
    status: "booked",
    isPublished: true,
    sellerType: "private",
    seller: {
      ...demoSeller,
      id: "seller-2",
      sellerType: "private",
      name: "Karan Singh",
      phone: "+91 9876543210",
    },
    buyer: null,
    images: [
      {
        id: "img-4",
        listingId: "car-3",
        imageUrl: "",
        isFeatured: true,
        sortOrder: 0,
      },
    ],
    documents: [],
    createdAt: "2026-03-22T10:00:00.000Z",
  },
];

export const demoInquiries: Inquiry[] = [
  {
    id: "inq-1",
    listingId: "car-1",
    name: "Harsh Gupta",
    phone: "+91 9988776655",
    email: "harsh@example.com",
    message: "Need more photos and best price for the Thar.",
    carTitle: "Mahindra Thar 2022",
    createdAt: "2026-03-25T11:15:00.000Z",
  },
  {
    id: "inq-2",
    listingId: "car-2",
    name: "Simran Arora",
    phone: "+91 8877665544",
    email: "simran@example.com",
    message: "Please share finance options for the Creta.",
    carTitle: "Hyundai Creta 2021",
    createdAt: "2026-03-24T14:45:00.000Z",
  },
];
